develop:
  project: python
  hosts:
    local:
      ip: 192.168.1.220
      port: 22
      user: admin
      identity_file: ~/.ssh/deployer.id_rsa
  config:
    restart_container: true
    debug: true
    from: ./
    keep_releases: 5
    deploy_path: /home/admin/python-project/amazon-spider
    rsync:
      timeout: 300
      exclude:
        - .env
        - .git
      exclude_from:
      include:
      include_from:
      delete: false
    share:
      dirs:
        - storage
      files:
        - .env
    writable:
      mode: chown
      recursive: true
      sudo: true
      dirs:
      files:
    remove:
      dirs:
      files:
    docker:
      container: amazon-spider


production:
  project: python
  hosts:
    local:
      ip: 47.251.32.63
      port: 22
      user: root
      identity_file: ~/.ssh/id_rsa
  config:
    restart_container: true
    debug: true
    from: ./
    keep_releases: 5
    deploy_path: /home/ubuntu/python-project/amazon-spider
    rsync:
      timeout: 300
      exclude:
        - .env
        - .git
      exclude_from:
      include:
      include_from:
      delete: false
    share:
      dirs:
        - storage
      files:
        - .env
    writable:
      mode: chown
      sudo: true
      recursive: true
      dirs:

      files:
    remove:
      dirs:
      files:
    docker:
      container: amazon-spider
