production:
  project: python
  hosts:
    local:
      ip: 54.219.185.72
      port: 22
      user: ubuntu
      identity_file: ~/.ssh/id_rsa
  config:
    debug: true
    from: ./
    keep_releases: 5
    deploy_path: /var/www/html/cpa/backend
    rsync:
      timeout: 300
      exclude:

      exclude_from:
      include:
      include_from:
      delete: false
    share:
      dirs:
        - storage
      files:
        - .env
    writable:
      mode: chown
      recursive: true
      dirs:

      files:
    remove:
      dirs:
      files:
    docker:
      container: amazon-splider
